# -*- coding: utf-8 -*-
"""bugerorder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbtcGXGCqE1GjenGDPbFRMcpRS7W45z5
"""

print("hello waiter giving mi menu card")
print("*********************************")
print("Mini Burger (M) : $5 ")
print("Normal Burger (N): $8")
print("Large Burger (L) : $10")
print("Add Mushroom : For Mini and Normal = $1, For Large = $2")
print("Extra Cheese : $1")

"""Calculates the total cost of the burger order."""
size = input("Enter the size of the burger (M/N/L)")
Mushroom = input("DO you want to add Mushroom (Y/N)")
Cheese =input("Do you want to add extra cheese (Y/N)")

if size =="M":
  Cost=5
elif size =="N":
    Cost=8
elif size =="L":
    Cost=10
else:
    Print("Invalid Print")

if Mushroom =="Y":
  if size =="L":
    Cost+=2
  else:
    Cost+=1

if Cheese =="Y":
  Cost+=1
print("Total cost $


" +str (Cost))

# prompt: BMI program

"""Calculates the BMI."""

weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

bmi = weight / (height ** 2)

print("Your BMI is:", bmi)

if bmi < 18.5:
    print("You are underweight.")
elif 18.5 <= bmi < 25:
    print("You have a healthy weight.")
elif 25 <= bmi < 30:
    print("You are overweight.")
else:
    print("You are obese.")

# prompt: shoes order on Amazon program

print("Welcome to Amazon Shoe Store!")
print("*********************************")
print("Sneakers (S) : $50 ")
print("Boots (B): $80")
print("Sandals (Sa): $30")
print("Add Shoe Polish : For Sneakers and Sandals = $5, For Boots = $10")
print("Extra Insoles : $10")

"""Calculates the total cost of the shoe order."""
shoe_type = input("Enter the type of shoe (S/B/Sa)")
shoe_polish = input("Do you want to add shoe polish (Y/N)")
insoles = input("Do you want to add extra insoles (Y/N)")

if shoe_type == "S":
  Cost = 50
elif shoe_type == "B":
    Cost = 80
elif shoe_type == "Sa":
    Cost = 30
else:
    print("Invalid shoe type")

if shoe_polish == "Y":
  if shoe_type == "B":
    Cost += 10
  else:
    Cost += 5

if insoles == "Y":
  Cost += 10
print("Total cost $ " + str(Cost))

# prompt: making car program

print("Welcome to the Car Dealership!")
print("*********************************")
print("Sedan (S) : $25000 ")
print("SUV (U): $40000")
print("Hatchback (H): $18000")
print("Add Sunroof : For Sedan and Hatchback = $1000, For SUV = $2000")
print("Leather Seats : $2000")

"""Calculates the total cost of the car."""
car_type = input("Enter the type of car (S/U/H)")
sunroof = input("Do you want to add a sunroof (Y/N)")
leather_seats = input("Do you want to add leather seats (Y/N)")

if car_type == "S":
  Cost = 25000
elif car_type == "U":
    Cost = 40000
elif car_type == "H":
    Cost = 18000
else:
    print("Invalid car type")

if sunroof == "Y":
  if car_type == "U":
    Cost += 2000
  else:
    Cost += 1000

if leather_seats == "Y":
  Cost += 2000
print("Total cost $ " + str(Cost))

# prompt: built a building program

print("Welcome to the Building Construction Company!")
print("*********************************")
print("Small Building (S) : $50000 ")
print("Medium Building (M): $100000")
print("Large Building (L): $200000")
print("Add Swimming Pool : For Small and Medium = $10000, For Large = $20000")
print("Add Extra Floor : $50000")

"""Calculates the total cost of the building."""
building_size = input("Enter the size of the building (S/M/L)")
swimming_pool = input("Do you want to add a swimming pool (Y/N)")
extra_floor = input("Do you want to add an extra floor (Y/N)")

if building_size == "S":
  Cost = 50000
elif building_size == "M":
    Cost = 100000
elif building_size == "L":
    Cost = 200000
else:
    print("Invalid building size")

if swimming_pool == "Y":
  if building_size == "L":
    Cost += 20000
  else:
    Cost += 10000

if extra_floor == "Y":
  Cost += 50000
print("Total cost $ " + str(Cost))

# prompt: create a bank account in bank  program

class BankAccount:
    def __init__(self, name, initial_balance=0):
        self.name = name
        self.balance = initial_balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposit successful. New balance: ${self.balance}")

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient funds.")
        else:
            self.balance -= amount
            print(f"Withdrawal successful. New balance: ${self.balance}")

    def get_balance(self):
        print(f"Current balance: ${self.balance}")


def create_account():
    name = input("Enter your name: ")
    initial_balance = float(input("Enter initial deposit amount: "))
    account = BankAccount(name, initial_balance)
    print(f"Account created for {name} with initial balance: ${initial_balance}")
    return account


if __name__ == "__main__":
    account = create_account()











# prompt: create a bank account in bank  program

class BankAccount:
    def __init__(self, name, initial_balance=0):
        self.name = name
        self.balance = initial_balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposit successful. New balance: ${self.balance}")

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient funds.")
        else:
            self.balance -= amount
            print(f"Withdrawal successful. New balance: ${self.balance}")

    def get_balance(self):
        print(f"Current balance: ${self.balance}")


def create_account():
    name = input("Enter your name: ")
    initial_balance = float(input("Enter initial deposit amount: "))
    account = BankAccount(name, initial_balance)
    print(f"Account created for {name} with initial balance: ${initial_balance}")
    return account


if __name__ == "__main__":
    account = create_account()